### ISSUE TITLE
async or configure timeout

### ISSUE THREAD

**Issue by davidosomething** [rachartier/tiny-code-action.nvim#10]
in code action finder:

	local all_results, err = vim.lsp.buf_request_sync(opts.bufnr, "textDocument/codeAction", params, 1000)

can you make the 1000 configurable, or switch to async request? usually for my many slow LSPs the first request will timeout and i get `no code actions` until LSPs have warmed up

**Comment by rachartier** [comment]
Hello,

It is normally done. I've increase it to be 2000, but it is now configurable with `opts.lsp_timeout`

**Comment by rachartier** [comment]
It is now async, so `opts.lsp_timeout` is now unused. Can you tell me if it works for you ? Thanks !

**Comment by davidosomething** [comment]
lgtm!
