### ISSUE TITLE
Error when using with rust-analyzer

### ISSUE THREAD

**Issue by jla2000** [rachartier/tiny-code-action.nvim#18]
When using this plugin in my rust projects, and executing `code_action()` there is either no reaction or this error pops up:
```
E5108: Error executing lua ...ugin-tiny-code-action.nvim/lua/tiny-code-action/init.lua:119: attempt to index field 'user_data' (a nil value)
stack traceback:
	...ugin-tiny-code-action.nvim/lua/tiny-code-action/init.lua:119: in function 'code_action_finder'
	...ugin-tiny-code-action.nvim/lua/tiny-code-action/init.lua:202: in function 'code_action'
	[string ":lua"]:1: in main chunk
```

In other projects e.g. lua config the plugin works just fine

**Comment by rachartier** [comment]
Ah yes... I changed something yesterday to remove the deprecated method. I will take a look.
In the meantime, you can set your branch to 1f2dcff00e74ddacba37373c57428ee784392f09 in lazy.nvim.

I'll get back to you once I've fixed the issue.

**Comment by rachartier** [comment]
What are your neovim version?

**Comment by jla2000** [comment]
Thanks for the quick reply :)
https://github.com/rachartier/tiny-code-action.nvim/commit/1f2dcff00e74ddacba37373c57428ee784392f09 works fine
