### ISSUE TITLE
default `delta` backend doesn't work

### ISSUE THREAD

**Issue by xarthurx** [rachartier/tiny-code-action.nvim#22]
```
		{
			"rachartier/tiny-code-action.nvim",
			dependencies = {
				{ "nvim-lua/plenary.nvim" },
				{ "nvim-telescope/telescope.nvim" },
			},
			event = "LspAttach",
			config = function()
				require("tiny-code-action").setup({
          backend = "delta",
        })
			end,
		},

```

When using `backend = "vim"` or doesn't overwrite it, things are fine.
But when changing it to `delta`, errors will occor:
![image](https://github.com/user-attachments/assets/fc778f3b-41aa-4e37-aeda-14d10c9916cf)

**Comment by rachartier** [comment]
You need to install `delta` first: [https://dandavison.github.io/delta/installation.html](https://dandavison.github.io/delta/installation.html)

**Comment by NakhodaAmir** [comment]
Hello. Im currently receiving a similar problem when setting backend to "delta".
I have downloaded Delta and set it up already.

![Image](https://github.com/user-attachments/assets/492a84e5-f468-499d-8a67-53f103ba1ac1)

**Comment by rachartier** [comment]
What's your shell?

**Comment by NakhodaAmir** [comment]
powershell

**Comment by rachartier** [comment]
`echo` should be available in `cmd` and `powershell`. Are you able to type `echo "ok"` in `powerhsell` and see a result ?

**Comment by NakhodaAmir** [comment]
The plug-in works when I use the Vim backend but doesn’t when I use the delta backend

**Comment by LevelFoRce** [comment]
Yeah I get the same error as this guy. I am using the LazyVim distribution btw. I have delta installed using scoop, I have setup tiny code action using opts = {}. And delta doesn't work with ANY picker, snacks, telescope, fzf, and buffer too!
