### ISSUE TITLE
Do not deep merge `config.telescope_opts`

### ISSUE THREAD

**Issue by serhez** [rachartier/tiny-code-action.nvim#23]
Deep merging `config.telescope_opts` may cause an invalid Telescope config. For instance, if you want to use `layout_strategy = "bottom_pane"`, Telescope does not support `layout_config.preview_height` being set. Even if this plugin's user does not set this option, the deep merge of the configs sets it, which causes an error when using Telescope. My workaround is the following:

```lua
require("tiny-code-action").setup({
    telescope_opts = {
        sorting_strategy = "ascending",
        layout_strategy = "bottom_pane",
    },
})
    
-- Remove the `telescope_opts.layout_config.preview_height` field
-- as it is not supported by the layout strategy `bottom_pane`
-- and it is always set due to the plugin using `vim.tbl_deep_extend`
-- to merge the default config with the user config
require("tiny-code-action").config.telescope_opts.layout_config = {
    width = 1.0,
    height = 25,
    preview_cutoff = 1,
}
```

However, this workaround is not ideal because it uses internal variable names which may change over time, which will break this code.

Thanks for reading!

**Comment by rachartier** [comment]
Thank you a lot !

It should now be fixed. Can you please test it ?

**Comment by serhez** [comment]
It works! Thanks :)
