### ISSUE TITLE
Implement missing methods action not working (Gopls)

### ISSUE THREAD

**Issue by NicolasGB** [rachartier/tiny-code-action.nvim#25]
Hi, first of all thanks for your plugin it has been so useful.

I found  a bug, this is the first time a code-action is not working for me, when i try to implement missing methods in golang i get the following error:

![image](https://github.com/user-attachments/assets/fdeb9961-10b8-4438-bd3c-d89504f11b27)

This code snippet should allow the reproduction:

```go
type MyInter interface {
	Foo()
}

type Impl struct{}

var _ MyInter = (*Impl)(nil)
```

Simply place the cursor on the line `var _ MyInter ...`, trigger the code-action and select `Declare missing methods  of MyInter`.

At first i thought it would be an lsp related error but when I try with `:lua vim.lsp.buf.code_action()` and select the same action, it does work as intended.

Let me know if i can provide any more information.

**Comment by rachartier** [comment]
Hello, thank you!

Unfortunately, I cannot seem to reproduce this issue.

- How have you configured gopls?
- What is your Neovim version?

![debug_tinycodeaction](https://github.com/user-attachments/assets/ad99b347-9539-4133-bbf7-a055b6694b23)

**Comment by rachartier** [comment]
Thanks again, it was indeed a change in the last nightly build.

It should now be fixed!

**Comment by NicolasGB** [comment]
It does indeed work as expected, thanks for being so fast!
