### ISSUE TITLE
Feature Request - Support only code action kind request filter

### ISSUE THREAD

**Issue by weilbith** [rachartier/tiny-code-action.nvim#27]
Hey 👋🏾 

First of all, thanks for your cool plugin! 🙏🏾 

Quite often, I'm faced with way too many code actions from (all) the language server(s). But might have a specific intend to query the code actions. Like I wanna fix a diagnostic or do some refactoring. For such a case it would be very helpful if is possible to call the `code_action` function of this plugin with a filter. 
This filter is natively supported by the language server protocol specification. It is part of the `context` request parameter and is called `only`. This takes an array of `CodeActionKind`s the server should respond with "only". Would be phenomenal if your plugin could maybe just transparently forwards this data somehow? It would allow users of your plugin to create designated keybindings, or any other trigger logic, for specific purposes like mentioned above (fixing, refactoring, ...).

What do you think about this feature? Would love to discuss it further. 🙃 
Thank you very much in advance!

**Comment by rachartier** [comment]
Hi,
Thanks!

That's a nice idea.

You can filter the code actions by setting the `filter` option.

```lua
{
    str = "..." -- Filter to title
    kind = "refactor" -- Filter to the kind
    client = "omnisharp" -- Filter to the client
}
```

Example:
```lua

require("tiny-code-action").code_action({
    kind = "refactor",
    str = "Wrap"
})
```

What do you think of that ? You can update to the latest version and try if you want!

**Comment by weilbith** [comment]
Thank you very much! That helped.
