### ISSUE TITLE
No code actions available

### ISSUE THREAD

**Issue by s1n7ax** [rachartier/tiny-code-action.nvim#3]
When I run the `require("tiny-code-action").code_action()` function via keymap or manually, `No code actions` notification shows up. Default code action select shows available actions correctly as you can see in the video

https://github.com/user-attachments/assets/dab56834-1db4-4328-a28b-26ea1c0855cd

```lua
return {
	'rachartier/tiny-code-action.nvim',
	keys = {
		{
			'<leader>A',
			function()
				require('tiny-code-action').code_action()
			end,
			desc = 'code actions',
			noremap = true,
			silent = true,
		},
	},
	dependencies = {
		{ 'nvim-lua/plenary.nvim' },
		{ 'nvim-telescope/telescope.nvim' },
	},
	event = 'LspAttach',
	config = true,
}
```

**Comment by rachartier** [comment]
I will take a look. What language server are you using ?

**Comment by s1n7ax** [comment]
@rachartier It's working with `jdtls`.

![image](https://github.com/user-attachments/assets/c1eb03cc-d645-4a9b-a8f1-5cf0be5e61d8)

I'm running LazyVim and it's using vtsls as Language server for typescript. You happened to have a some kind of a condition?

**Comment by rachartier** [comment]
Yes I've tried with vtsls, 
Could you please send me a repo link for the code example that you are testing (with dependencies) ? 

With that, I could maybe reproduce the issue

**Comment by zerochae** [comment]
same

- preview function in tiny-code-action/action.lua

`action.edit` is nil

![image](https://github.com/user-attachments/assets/e26d80b9-f1c0-45ec-bc28-9470fc0b4869)

**Comment by zerochae** [comment]
same

- preview function in tiny-code-action/action.lua

`action.edit` is nil

![image](https://github.com/user-attachments/assets/e26d80b9-f1c0-45ec-bc28-9470fc0b4869)

```ts
test.ts

interface Test {
  foo(): void;
}

export const test: Test = {}; // do code action
```

```lua
-- inspact action table

{
  command = {
    arguments = { {
        documentChanges = { {
            edits = { {
                newText = '{\n    foo: function(): void {\n        throw new Error("Function not implemented.");\n    }\n}',
                range = {
                  ["end"] = {
                    character = 28,
                    line = 4
                  },
                  start = {
                    character = 26,
                    line = 4
                  }
                }
              } },
            textDocument = {
              uri = "/my-path/apis/user/test.ts",
              version = 0
            }
          } }
      } },
    command = "_typescript.applyWorkspaceEdit",
    title = "Add missing properties"
  },
  kind = "quickfix",
  title = "Add missing properties"
}
```

**Comment by ouuan** [comment]
I noticed that this plugin shows "no code actions available" immediately when the language server is still loading, while `actions-preview.nvim` waits until the language server is loaded.

**Comment by rachartier** [comment]
> I noticed that this plugin shows "no code actions available" immediately when the language server is still loading, while `actions-preview.nvim` waits until the language server is loaded.

I don't really get it. I'm not waiting for the LSPs to load, but that doesn't change how it works in the background. Once the LSPs are loaded, I show their code actions.

**Comment by ouuan** [comment]
Oops, I failed to reproduce this. Maybe there was something wrong with my testing.

**Comment by ouuan** [comment]
`actions-preview.nvim` waits until the code action is loaded:

https://github.com/user-attachments/assets/656a8eb3-c3c7-4510-9a96-e66c96d9eab8

`tiny-code-action.nvim` shows no code action available immediately:

https://github.com/user-attachments/assets/cffbf959-e4e7-4854-b3e4-aaa796368e26

You can see the keystrokes and language server loading status at the bottom.

**Comment by s1n7ax** [comment]
@rachartier I have not committed this plugin since I couldn't get it working.

I don't have anything related to `typescript` other than lazy extra I think which I have not added into the repository.

```json
# lazyvim.json

{
  "extras": [
    "lazyvim.plugins.extras.lang.docker",
    "lazyvim.plugins.extras.lang.rust",
    "lazyvim.plugins.extras.lang.tailwind",
    "lazyvim.plugins.extras.lang.typescript",
    "lazyvim.plugins.extras.lang.yaml"
  ],
  "news": {
    "NEWS.md": "6520"
  },
  "version": 6
}
```

Project is just a nextjs starter project I've created by running `npx create-next-app@latest`.

https://github.com/s1n7ax/lazyvim-dotnvim

**Comment by rachartier** [comment]
> `actions-preview.nvim` waits until the code action is loaded:
> actions-preview.mp4
> 
> `tiny-code-action.nvim` shows no code action available immediately:
> tiny-code-action.mp4
> 
> You can see the keystrokes and language server loading status at the bottom.
> 
> I used the template code from https://docs.rs/eframe/latest/eframe/. It does not really matter, just using a big crate to make the loading time longer.

It is not the same issue as @s1n7ax. If you want you can open a new one.

**Comment by rachartier** [comment]
> @rachartier I have not committed this plugin since I couldn't get it working. In my case, LSP has started and working fine. Though it's running I don't get any code actions. I will debug this when in the weekend and let you know more info.
> 
> I don't have anything related to `typescript` other than lazy extra I think which I have not added into the repository.
> 
> ```json
> # lazyvim.json
> 
> {
>   "extras": [
>     "lazyvim.plugins.extras.lang.docker",
>     "lazyvim.plugins.extras.lang.rust",
>     "lazyvim.plugins.extras.lang.tailwind",
>     "lazyvim.plugins.extras.lang.typescript",
>     "lazyvim.plugins.extras.lang.yaml"
>   ],
>   "news": {
>     "NEWS.md": "6520"
>   },
>   "version": 6
> }
> ```
> 
> Project is just a nextjs starter project I've created by running `npx create-next-app@latest`.
> 
> https://github.com/s1n7ax/lazyvim-dotnvim


Thank a lot for this informations.
I did some debugs, and I think it is now resolved:

![tinycodeaction_debug_3](https://github.com/user-attachments/assets/714adf0d-4550-41f6-a9fc-5eaf6e6128a3)

**Comment by s1n7ax** [comment]
@rachartier Code actions are retrieved successfully from this line

https://github.com/rachartier/tiny-code-action.nvim/blob/8fb55da53c5ed3f5a25ad07916d40f50b0b59172/lua/tiny-code-action/init.lua?plain=1#L95

But after this for loop, `results` array is empty.

https://github.com/rachartier/tiny-code-action.nvim/blob/8fb55da53c5ed3f5a25ad07916d40f50b0b59172/lua/tiny-code-action/init.lua?plain=1#L104-L124

This is the structure of the `all_results` variable

![image](https://github.com/user-attachments/assets/23516a38-f437-4953-a79e-ce1f39ea1dc5)

I have these language servers running

```
 Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: /home/s1n7ax/.local/state/nvim/lsp.log
 Detected filetype:   typescriptreact
 
 4 client(s) attached to this buffer: 
 
 Client: tailwindcss (id: 1, bufnr: [3])
 	filetypes:       aspnetcorerazor, astro, astro-markdown, blade, clojure, django-html, htmldjango, edge, eelixir, elixir, ejs, erb, eruby, gohtml, gohtmltmpl, haml, handlebars, hbs, html, htmlangular, html-eex, heex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte, templ, rust
 	autostart:       true
 	root directory:  /home/s1n7ax/Workspace/next-test
 	cmd:             /home/s1n7ax/.nix-profile/bin/tailwindcss-language-server --stdio
 
 Client: eslint (id: 2, bufnr: [3])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx, vue, svelte, astro
 	autostart:       true
 	root directory:  /home/s1n7ax/Workspace/next-test
 	cmd:             /home/s1n7ax/.nix-profile/bin/vscode-eslint-language-server --stdio
 
 Client: emmet_language_server (id: 3, bufnr: [3])
 	filetypes:       css, eruby, html, htmldjango, javascriptreact, less, pug, sass, scss, typescriptreact, htmlangular, rust
 	autostart:       true
 	root directory:  /home/s1n7ax/Workspace/next-test
 	cmd:             /home/s1n7ax/.nix-profile/bin/emmet-language-server --stdio
 
 Client: vtsls (id: 4, bufnr: [3])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  /home/s1n7ax/Workspace/next-test
 	cmd:             /home/s1n7ax/.local/share/nvim/mason/bin/vtsls --stdio
 
 Configured servers list: marksman, lua_ls, vtsls, emmet_language_server, nil_ls, jdtls, docker_compose_language_service, cssls, tailwindcss, jsonls, taplo, ruff_lsp, pyright, eslint, yamlls, dockerls
```

**Comment by rachartier** [comment]
Did you update it first ?

**Comment by rachartier** [comment]
Oh... We did fix it at the same time haha!

**Comment by rachartier** [comment]
Sorry for the inconveniences and delay to be resolved.

**Comment by s1n7ax** [comment]
Working
