### ISSUE TITLE
For Delta, what do you think about not including --color-only in all paths?

### ISSUE THREAD

**Issue by cameronr** [rachartier/tiny-code-action.nvim#5]
I prefer Delta's use of colors to distinguish additions / subtractions but including --color-only in all paths forces the +/- annotations.

https://github.com/rachartier/tiny-code-action.nvim/blob/5b175338e683afd2921fa24f7c81f1cca1c124b2/lua/tiny-code-action/backend/delta.lua#L41-L43

What do you think about not setting that at all or maybe only setting it in the default / no git / no config path:

https://github.com/rachartier/tiny-code-action.nvim/blob/5b175338e683afd2921fa24f7c81f1cca1c124b2/lua/tiny-code-action/backend/delta.lua#L30-L32

Thanks!

**Comment by rachartier** [comment]
Hello!
You're right. I've also simplified how to pass argurments to delta, now everything is configurable.

I let you take a look at the README if you want. But `--color-only` has been removed by default.

Thank you a lot !
