### ISSUE TITLE
Incorrect diff with rust analyzer

### ISSUE THREAD

**Issue by ouuan** [rachartier/tiny-code-action.nvim#7]
Original code:

```rust
pub fn foo() -> i32 {
    let x = 1;
    x + x
}
```

Plugin diff:

```diff
 pub fn foo() -> i32 {
-    let x = 1;
-    x + x
+    1
+ + x1
 }
```

Actual result:

```rust
pub fn foo() -> i32 {
    1 + 1
}
```

Plugin diff:

```diff
 pub fn foo() -> i32 {
-    let x = 1;
-    x + x
+    consX:i32  x = 1;
+    X + X
 }
```

Actual result:

```rust
pub fn foo() -> i32 {
    const X: i32 = 1;
    X + X
}
```

`actions-preview.nvim` works as expected.

**Comment by rachartier** [comment]
Hello,
Which LSP do you use?

**Comment by ouuan** [comment]
> Which LSP do you use?

In the title, rust analyzer.

**Comment by rachartier** [comment]
Maybe did you configure your LSP ? I have the default config, and it did not shows the same code actions as yours:

![image](https://github.com/user-attachments/assets/3ce02bc6-d6ab-4485-9f01-53230f6c8b2c)

![image](https://github.com/user-attachments/assets/79c5ed60-1b87-426c-a4e9-a987302aaf32)

**Comment by ouuan** [comment]
I'm not sure, but the problem also exists in your second screenshot.

**Comment by rachartier** [comment]
It should be good now. Can you test it please ?

**Comment by ouuan** [comment]
![image](https://github.com/user-attachments/assets/4cf8960d-2649-4dac-9836-7890ebe66193)

![image](https://github.com/user-attachments/assets/b158fb1f-bfea-46a8-a826-c23390c39bac)

There is an extra new line in the diff.

**Comment by rachartier** [comment]
It should now be ok (I hope) as of commit https://github.com/rachartier/tiny-code-action.nvim/commit/8fb55da53c5ed3f5a25ad07916d40f50b0b59172:

![image](https://github.com/user-attachments/assets/2e375ba7-eaf8-4b1c-b0c1-48c8f08f4696)

**Comment by ouuan** [comment]
> ![image](https://private-user-images.githubusercontent.com/30581822/352500503-4cf8960d-2649-4dac-9836-7890ebe66193.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDQ4NTgsIm5iZiI6MTcyMjAwNDU1OCwicGF0aCI6Ii8zMDU4MTgyMi8zNTI1MDA1MDMtNGNmODk2MGQtMjY0OS00ZGFjLTk4MzYtNzg5MGViZTY2MTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE0MzU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMWU3ZGY2MTBjYjdkMTA4MDRjNjM0NmViN2Q3MWU3YTM0ZWI5M2FlZDdlMzU0ODYzMjJiNjUwZTdkMWEwNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.06VgcjGgHI_5dJfPG6PztotHnLOhljG96iU_419-a9U)
> 
> ![image](https://private-user-images.githubusercontent.com/30581822/352500538-b158fb1f-bfea-46a8-a826-c23390c39bac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDQ4NTgsIm5iZiI6MTcyMjAwNDU1OCwicGF0aCI6Ii8zMDU4MTgyMi8zNTI1MDA1MzgtYjE1OGZiMWYtYmZlYS00NmE4LWE4MjYtYzIzMzkwYzM5YmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE0MzU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MWY5ZWNhYzdkZmNmMmYwNDA1MTAyZWQ4ZTg4ZGJlZTE5NTY4OGM4YTEyOWI4MGVmMDdkMDhmOWQ3ODIyZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NapSIl-e0whJtAsR_wbq17JB_1RqSPZQrcBfK-bUQFI)
> 
> There is an extra new line in the diff.

This one is still the same. I'm not sure why you are seeing a different list of available code actions. I'm using `rust-analyzer 1 (4afe0d5393 2024-07-21)` and `cargo 1.80.0 (376290515 2024-07-16)`.

**Comment by ouuan** [comment]
I see that this plugin uses custom logic to parse the language server outputs. Can we use `vim.lsp.util.apply_text_edits` instead? See https://github.com/aznhe21/actions-preview.nvim/blob/9f52a01c374318e91337697ebed51c6fae57f8a4/lua/actions-preview/action.lua#L59-L66

**Comment by rachartier** [comment]
> `apply_text_edits`

Unfortunately, LSPs send back textChanges for some actions, which is not supported (I think, I haven't found anything about it) with native LSP in Neovim, so that's why I used custom logic

I really can't have the same actions as yours. I do not understand why, I did install `rust-analyzer (2024-07-22)` (as `2024-07-21` was not in mason) and `cargo 1.80.0 (376290515 2024-07-16)`. I've tried to get code actions for every characters in the demo file, and I can't have the same as yours... Do you have some specifics configurations? It will made my life easier if I can debug a real example.

**Comment by ouuan** [comment]
> Do you have some specifics configurations?

I don't think so. I just use the default configuration from nvim-lspconfig.

**Comment by rachartier** [comment]
Okay I did reproduce the issue.

You probably have `rustacean` installed. I've modified the code to merge lines if needed, so you shouldn't have the issue anymore.
